# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-01 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='color_tag',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='photo',
            name='modify_date',
            field=models.DateField(auto_now=True),
        ),
    ]
